<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "localhost");
if (!defined("PJ_USER")) define("PJ_USER", "root");
if (!defined("PJ_PASS")) define("PJ_PASS", "");
if (!defined("PJ_DB")) define("PJ_DB", "ahmet_newbooking");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "");
if (!defined("PJ_USE_IV")) define("PJ_USE_IV", "0");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/Ahmet/newbooking/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "D:/PHP/PHP8.212/htdocs/Ahmet/newbooking/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "http://localhost/Ahmet/newbooking/");
if (!defined("PJ_SALT")) define("PJ_SALT", '69E9THT1');
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "MTIyMjI1MjEwMjQ2NDM0NzgxMDU1MDg4NjgzNTgxNTA4NzM0MzQ1ODYzNDg0OTgyMDMwNTk0MDgxMzkwNTAxODk3NzYwMjUxNjIxNTQxMTM5MTk0ODU5MjczMTM3NTM2ODcwMSA2MjAwNzU0MzI1OTA0MjM4ODU2Mzc0NTgyNjkwMjIwNDEwOTc3OTUzODEyODQxMDI3Nzc2MjczODAyODQ2MzU5ODY0MTE1OTY4NDI0Nzk3NTYwMjMyMDU1OTQ3MzM4MTg3NiA3OTY4NDQ3NTY4NzM2MTc5NTY1MTk2NzYzMjI5OTAyNzA0MDUzNjcyNzk1Nzk5MDE4NzI3NjU5NzU1ODkwNjIzNjk3MjQzMjQzMDQ3MTY1MDQyNDU5OTQ4NDI3NTczNzA3MyAxNjg4NzkzNTg2MjA0NzA2MDEwNzkwOTY4MTg3Nzc1MzQwODc4NTEzMzMxNzk2ODY2NjczODMwMjY1NTQ1ODE3NjY1MzQ5NDg3OTY2MzEyOTc5NTYxMjg4NTM2NTM5MTQxMzQgMTM4NzkxNzA1NjQ0ODE4NDE0NzAwMzgzMTExMTI2MTIwMTcwMTUxNTAwNzQyMDI1MzEzNzM3NDYxODMzODk1NjUwOTIwMjgxODEzNDE2MTI1Njg3OTc0ODgxMjk3MDYzNDk0MyA4MjgyMzA3ODg5ODIwOTE3ODQ1NzQ2MjY5NjkyODg0MDAxMjk3MTQ4MzQ5OTI2MjgwODk0ODY2NTk4MTI4MDU3NDMzNjY5NDgzOTUyMDYwOTU3MTIyMzgwNjExNTk1OTY2MjQgMTYzNTIzNzM4OTAxNzkxNTYzOTE3MTgwNjU4NDU0NTI1MDkyNjg1NTY0OTcyMjI4NDk3OTk0MzI0ODE4MDM4NDI4NjY2Mjk0OTg5NDA2NzM0Mjc3MjM1NjAzMTg2ODQxMTMw");
?>